[package]
name = "git-flow"
version = "0.1.0"
authors = ["matsumoto <r-matsumoto@zyyx.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
